### ISSUE TITLE
extra_requirements_txt configuration fails on dbt-spark[PyHive] adapter

### ISSUE THREAD

**Issue by onesuper** [yu-iskw/action-sqlfluff#20]
Since dbt-spark[PyHive] has binary dependency of `libsasl2 `. I work-around this problem by changing the Dockerfile for now.

**Comment by yu-iskw** [comment]
I put the installation of `libsasl2` to `Dockerfile`.

- https://github.com/yu-iskw/action-sqlfluff/pull/21
