### ISSUE TITLE
Please add build essentials (gcc) to Dockerfile

### ISSUE THREAD

**Issue by onesuper** [yu-iskw/action-sqlfluff#24]
When the action attempts to install libsasl2, it failed with missing gcc error.

**Comment by yu-iskw** [comment]
@onesuper Can you send a pull request? As far as I am using the action, the situation can't occur.

**Comment by onesuper** [comment]
Sure

**Comment by onesuper** [comment]
Hi @yu-iskw, I have added #26 to resolve this problem. An one-line commit!

**Comment by yu-iskw** [comment]
@onesuper Thank you for the PR. I have just released v3.3.1. Can you give it a try?

- https://github.com/yu-iskw/action-sqlfluff/releases/tag/v3.3.1

**Comment by yu-iskw** [comment]
Apart from that, I will test the action with `dbt-spark[pyHive]`, instead of `dbt-spark`. 

- https://github.com/yu-iskw/action-sqlfluff/pull/27

**Comment by onesuper** [comment]
Already picked up the latest version in our dbt project. 

Good Luck!

**Comment by yu-iskw** [comment]
Thank you for the feedback. If there is anything I can help, please let me know.
