### ISSUE TITLE
Wrong JSON output with tee and dbt templater

### ISSUE THREAD

**Issue by psg2** [yu-iskw/action-sqlfluff#41]
When running with the dbt templater the process might add more output lines that aren't actual JSON format and then it will fail trying to run jq [here](https://github.com/yu-iskw/action-sqlfluff/blob/main/entrypoint.sh#L77)

e.g:

```
[0m14:02:51  Unable to do partial parsing because config vars, config profile, or config target have changed
[0m14:02:52  Unable to do partial parsing because config vars, config profile, or config target have changed
[{"filepath":  ...
```

I think one possible solution is to replace tee with `--write-output` from sqlfluff itself that was added since version 0.10.1, this way the resulting file only contains the final report.

I could try to make a PR to fix this, what do you think?

**Comment by yu-iskw** [comment]
Sorry for the delay of my reply. If it still occurs, please feel free to reopen it.
