### ISSUE TITLE
Action doesn't pick up space in paths

### ISSUE THREAD

**Issue by ImposterSy** [yu-iskw/action-sqlfluff#73]
Hi, 

There is an issue with including spacing in the 'paths' input for the action. I have tried several methods (ubuntu way of escaping space, env variables, repo variables) and nothing has worked out. 

![image](https://user-images.githubusercontent.com/42849284/223161418-02538f97-3ad0-4d26-b045-4acdfe31f4fd.png)

Thanks!

**Comment by kieronellis** [comment]
Remove the space from your path. It's probably general best practice not to include them anyway.

**Comment by ImposterSy** [comment]
> Remove the space from your path. It's probably general best practice not to include them anyway.

If that was in my control I would do it straight away! :)

**Comment by yu-iskw** [comment]
Surrounding the value with single quotes probably solves it.
