### ISSUE TITLE
sqlfluff v2.0

### ISSUE THREAD

**Issue by kounoike** [yu-iskw/action-sqlfluff#77]
maybe this action is not compatible sqlfluff v2.0 (I test with 2.0.3)
is there any update plan?

**Comment by yu-iskw** [comment]
I haven't watched the issue https://github.com/sqlfluff/sqlfluff/pull/4317 for a while. Is it ready to use sqlfluff 2.0 with dbt-core 1.4+? 

https://github.com/yu-iskw/action-sqlfluff/blob/main/requirements/requirements.txt#L4-L7

**Comment by kounoike** [comment]
I'm not familiar enough with the implementation to know why dbt-core is needed.
